// <auto-generated />
namespace TesteCrmall.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class FixedDataDeNascimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedDataDeNascimento));
        
        string IMigrationMetadata.Id
        {
            get { return "202011231743134_FixedDataDeNascimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
